kind: sim2real-transfer
version: 3

scenario: admission_control

algorithm:
  source: sim2real_bundle_14b/algorithm/admission.go

baseline:
  real:
    notes: |
      Note that inference objective is configured like the following

      ```yaml
      inferenceObjectives:
        - name: critical
          priority: 100
        - name: standard
          priority: 0
        - name: sheddable
          priority: -10
        - name: batch
          priority: -50
      ````

      Use the random picker plugin for the real baseline generation:

      ```yaml
      apiVersion: inference.networking.x-k8s.io/v1alpha1
      kind: EndpointPickerConfig
      plugins:
      - type: random-picker
      schedulingProfiles:
      - name: default
        plugins:
        - pluginRef: random-picker
          weight: 1
      ````

workloads:
- sim2real_bundle_14b/workloads/w1a_14b.yaml
- sim2real_bundle_14b/workloads/w1b_14b.yaml
- sim2real_bundle_14b/workloads/w1c_14b.yaml

hints:
  files:
  - sim2real_bundle_14b/README.md
  text: You need to override the saturation detection scheme in the legacy admission control in the treatment config generation by disabling it by making it ineffective using saturationDetector the values basically ineffective so the system is never considered saturation, resulting in an always admit policy when it reaches our controller.

context:
  files:
  - blis-context.md
  - gaie_context.md
  - llm-d-inference-scheduler-context.md
