kind: sim2real-transfer
version: 3

scenario: adaptive-routing

algorithm:
  source: sim2real_golden_correct/routers/router_adaptive.go
  config: sim2real_golden_correct/routers/policy_adaptive.yaml

baseline:
  sim:
    config: sim2real_golden_correct/routers/policy_baseline_322.yaml
  real:
    config: sim2real_golden_correct/routers/baseline_epp_template.yaml
    notes: |
      # The precise prefix well-lit path features the following config and can be found here: https://github.com/llm-d/llm-d/blob/main/guides/precise-prefix-cache-aware/gaie-kv-events/values.yaml#L116

      pluginsConfigFile: "precise-prefix-cache-config.yaml"
      pluginsCustomConfig:
        precise-prefix-cache-config.yaml: |
          apiVersion: inference.networking.x-k8s.io/v1alpha1
          kind: EndpointPickerConfig
          plugins:
            - type: single-profile-handler
            - type: tokenizer
              parameters:
                modelName: Qwen/Qwen3-32B
                udsTokenizerConfig:
                  socketFile: /tmp/tokenizer/tokenizer-uds.socket
            - type: precise-prefix-cache-scorer
              parameters:
                tokenProcessorConfig:
                  blockSize: 64
                indexerConfig:
                  speculativeIndexing: true
                  tokenizersPoolConfig:
                    modelName: Qwen/Qwen3-32B
                    local: null
                    hf: null
                    uds:
                      socketFile: /tmp/tokenizer/tokenizer-uds.socket
                kvEventsConfig:
                  topicFilter: "kv@"
                  concurrency: 4
                  discoverPods: false
                  zmqEndpoint: "tcp://*:5557"
            - type: kv-cache-utilization-scorer
            - type: queue-scorer
            - type: max-score-picker
          schedulingProfiles:
            - name: default
              plugins:
                - pluginRef: precise-prefix-cache-scorer
                  weight: 3.0
                - pluginRef: kv-cache-utilization-scorer
                  weight: 2.0
                - pluginRef: queue-scorer
                  weight: 2.0
                - pluginRef: max-score-picker


workloads:
  # - sim2real_golden_correct/workloads/workload_fm3_burst.yaml
  - sim2real_golden_correct/workloads/workload_fm5_short_output.yaml
  # - sim2real_golden_correct/workloads/workload_fm8_short_output_highrate.yaml

llm_config: admission_by60/llm_config.yaml

hints:
  files:
  - sim2real_golden_correct/README.md
  - sim2real_golden_correct/transfer_hint.md
  - sim2real_golden_correct/feedback.md
  notes: Please check upstream GAIE for scorers that already exist and reuse instead of implementing new ones.

context:
  files:
  - blis-context.md
  - gaie_context.md
  - llm-d-inference-scheduler-context.md